language: cpp

os:
    - osx

addons:
  homebrew:
    packages:
    - qt
    - opencv

before_install:
    - brew link qt --force
    
script:
    - qmake -makefile -o Makefile DeepLabel.pro
    - make -j4
