language: cpp

os:
    - osx

before_install:
    - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - brew update
    - brew install qt opencv
    - brew link qt --force
    
script:
    - qmake -makefile -o Makefile DeepLabel.pro
    - make -j4
