language: cpp

os:
    - osx
addons:
  homebrew:
    packages:
    - qt
    - opencv
    update: true
    
before_install:
    - brew link qt --force
    
script:
    - qmake -makefile -o Makefile DeepLabel.pro
    - make -j4
